### ISSUE TITLE
Can't handle unknown values

### ISSUE THREAD

**Issue by cameronweston** [nanamake/vcd2json#4]
I tried using this for a simple waveform which has unknown values during some of the clock cycles. This caused the parser to crash when parsing the file. 
[wishbone.txt](https://github.com/nanamake/vcd2json/files/11907914/wishbone.txt)

**Comment by nanamake** [comment]
This script only supports 4 values 0/1/x/z. sorry.

**Comment by nanamake** [comment]
Since there is no reply, I will close this issue.
