### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by polyee13** [nanamake/vcd2json#5]
I've modified the example.py Example 2 to use my own VCD that was dumped out of VCS 2021

I'm getting this traceback. I believe it's something about the content of the VCD because if I copy my contents into your timer.vcd I get the same error. 
Example 2
----------------------------------------
Traceback (most recent call last):
  File "spi.py", line 54, in <module>
    example2()
  File "spi.py", line 45, in example2
    extractor = WaveExtractor('sim.vcd', 'spi.json', path_list)
  File "/home/anthony/gitspaces/vcd2json/vcd2json.py", line 30, in __init__
    self._setup()
  File "/home/anthony/gitspaces/vcd2json/vcd2json.py", line 93, in _setup
    path_list, path_dict = create_path_dict(fin)
  File "/home/anthony/gitspaces/vcd2json/vcd2json.py", line 70, in create_path_dict
    if words[0] == '$enddefinitions':
IndexError: list index out of range

**Comment by polyee13** [comment]
@anders-code Please see above.

**Comment by nanamake** [comment]
The cause cannot be determined from the traceback.
To identify it, you will need the edited code and the header of the VCD file.

**Comment by polyee13** [comment]
Here is a very simplified example. just a heartbeat sim. I'm pretty confident it's something specific about the VCD format from Synopsys since this is now the 2nd sim that results in the same error.
[heartbeat.zip](https://github.com/nanamake/vcd2json/files/13903842/heartbeat.zip)

**Comment by nanamake** [comment]
I modified vcd2json.py to skip blank lines and real value lines in the VCD file. The error was due to the VCD file containing blank lines. Although real type diagrams are not supported, but real value lines can be included in the VCD file.

**Comment by polyee13** [comment]
Are you putting up a PR for it? Or can you provide the code changes here?

**Comment by nanamake** [comment]
The master vcd2json.py has been modified. Please download it.
The previous comment was poorly written so I rewrote it. Sorry.

**Comment by polyee13** [comment]
Just pulled in the changes. It works perfectly now. Thanks! You may close the Issue.

**Comment by polyee13** [comment]
Ok, the script executes fine now. Please feel free to close.

One other thing I was curious about is instead of having clk as the first signal in the path list, say I had sclk for a SPI interface, it seems that the script doesn't detect the behavior of sclk as a signal itself. It's almost like it uses clk to sample sclk for wavedrom. Is this the nature of how wavedrom or the vcd is parsed?

Ideally, I would have liked just my SPI signals in the wavedrom plots, which helps a lot because it shortens the sampling window, allowing me to use wave_chunks that better represent a SPI transaction. I suppose I can modify the json post generated to get where I need to though.

**Comment by nanamake** [comment]
Most of the digital circuits are synchronous designs, so for simplicity I dedicated the first signal to the synchronous clock. It assumes that the clock is always running. This is not a limitation of WaveDrom or VCD.
